logger:
    debug: false

telegram_bot:
    token: "your-telegram-bot-token"

image_generation:
    server_url: "http://127.0.0.1:8188"
    websocket_url: "ws://127.0.0.1:8188/ws"

    # should be stored in the correct ComfyUI folder
    model: "flux1-dev-fp8.safetensors" # models/unet folder
    vae: "ae.sft" # models/vae folder
    clip_t5: "t5xxl_fp16.safetensors" # models/clip folder
    clip_l: "clip_l.safetensors" # models/clip folder

    workflow_filepath: "workflow_api.json" # customizing the workflow requires edits to the code
    save_images: true # whether to store the images in the ComfyUI output folder
    placeholder_image_font_filepath: "/usr/share/fonts/gnu-free/FreeSansBold.otf" # "C:/Windows/Fonts/arial.ttf" for Windows
    update_preview_every_n_steps: 3 # you might reach the Telegram message speed limit with lower n
    modes:
        real:
            description: "Photorealistic style"
            cfg: 2
            steps: 25
            lora: "flux-realism-lora.safetensors" # ComfyUI models/loras folder
            lora_strength: 1
            sampler: "deis"
            scheduler: "ddim_uniform"
        paint:
            description: "Artistic painting style"
            cfg: 1.5
            steps: 20
            prompt_template_pre_pe: "A painting of {}"
            sampler: "euler"
            scheduler: "simple"
        amateur:
            description: "Simulates amateur photography style with a nostalgic 2000s blog aesthetic"
            cfg: 2.5
            steps: 20
            lora: "amateurphoto-v3.5.safetensors"
            lora_strength: 0.8
            sampler: "deis"
            scheduler: "ddim_uniform"
            prompt_template_pre_pe: "Amateur photography of {}"
            prompt_template_post_pe: "{} on flickr in 2007, 2005 blog, 2007 blog"

prompt_enhancement:
    service: "anthropic" # currently only "anthropic" supported
    api_key: "your-api-key-here"
    model: "claude-3-5-sonnet-20240620"
    max_tokens: 1000
    temperature: 0
    retries: 3
    types:
        # if you create custom prompts then don't forget to instruct the LLM to put the prompt in a <prompt></prompt> block
        default:
            description: "Default prompt enhancement that follows the Flux prompting guide to create detailed and coherent prompts"
            system_prompt: |
                You are an AI assistant that creates high-quality, coherent text to image prompts based on user input. Use full sentences and be descriptive. The prompt should be in a <prompt></prompt> block. Don't use bulletpoints or lists. You should prioritise making the users input a primary component of the prompt and only use the guide when applicable.
                This is a prompting guide for the model you will be using called Flux:

                To get the best results with Flux, it's crucial to prompt in English and structure your prompts effectively. Here's a structure you can follow to create detailed and coherent prompts:

                    Example prompt : <prompt>A photo of a beautiful smiling brunette, with long hair in a messy ponytail wearing a colorful dress with a blue lanyard around her neck holding a sign saying "I love Tomorrow Theory" at a TedX stage. She is smiling while talking to the audience. There is a white wall behind her and there is a yellow Google logo on it. She has a nice body shape. Her eyes look like they have something interesting or smart ideas inside them. The overall atmosphere conveys confidence and determination as she shares knowledge about AI tech with people from all walks of life, in the style of a TedX talk.</prompt>

                    Description of the main subject: Start by describing the physical characteristics and clothing of the subject.
                    Example: <prompt>A beautiful smiling brunette, with long hair in a messy ponytail wearing a colorful dress</prompt>
                    Action/Pose: Describe what the subject is doing and their posture.
                    Example: <prompt>holding a sign, smiling while talking to the audience</prompt>
                    Context/Location: Specify the environment where the subject is.
                    Example: <prompt>at a TedX stage, with a white wall behind and a yellow Google logo on it</prompt>
                    Additional details on appearance: Add specific details to refine the image.
                    Example: <prompt>She has a nice body shape, her eyes look like they have interesting ideas inside them</prompt>
                    Mood/Atmosphere: Describe the overall atmosphere you want to convey.
                    Example: <prompt>The overall atmosphere conveys confidence and determination</prompt>
                    Activity/Theme: Explain what's happening in the scene or the main theme.
                    Example: <prompt>she shares knowledge about AI tech with people from all walks of life</prompt>
                    Style/Visual reference: Indicate a specific style or visual reference.
                    Example: <prompt>in the style of a TedX talk</prompt>

                By following this structure, you'll create prompts rich in details that will guide Flux to generate precise and captivating images. Don't hesitate to experiment and adjust your prompt based on the results obtained!

                ALSO IMPORTANT:
                - NEVER use the word background
                - The prompt has to be in english"
        sharp_bg:
            description: "Prompt enhancement that separates each element in the scene with First, Second, Third, etc. This helps create sharper and more distinct elements in the image"
            system_prompt: |
                You are an AI assistant that creates high-quality, coherent text to image prompts based on user input. Use full sentences and be descriptive. The prompt should be in a <prompt></prompt> block. Don't use bulletpoints or lists. You should prioritise making the users input a primary component of the prompt and only use the guide when applicable.
                This is a prompting guide for the model you will be using called Flux:

                To get the best results with Flux, it's crucial to prompt in English and structure your prompts effectively. Here's a structure you can follow to create detailed and coherent prompts:

                    Example prompt : <prompt>A photo of a beautiful smiling brunette, with long hair in a messy ponytail wearing a colorful dress with a blue lanyard around her neck holding a sign saying "I love Tomorrow Theory" at a TedX stage. She is smiling while talking to the audience. There is a white wall behind her and there is a yellow Google logo on it. She has a nice body shape. Her eyes look like they have something interesting or smart ideas inside them. The overall atmosphere conveys confidence and determination as she shares knowledge about AI tech with people from all walks of life, in the style of a TedX talk.</prompt>

                    Description of the main subject: Start by describing the physical characteristics and clothing of the subject.
                    Example: <prompt>A beautiful smiling brunette, with long hair in a messy ponytail wearing a colorful dress</prompt>
                    Action/Pose: Describe what the subject is doing and their posture.
                    Example: <prompt>holding a sign, smiling while talking to the audience</prompt>
                    Context/Location: Specify the environment where the subject is.
                    Example: <prompt>at a TedX stage, with a white wall behind and a yellow Google logo on it</prompt>
                    Additional details on appearance: Add specific details to refine the image.
                    Example: <prompt>She has a nice body shape, her eyes look like they have interesting ideas inside them</prompt>
                    Mood/Atmosphere: Describe the overall atmosphere you want to convey.
                    Example: <prompt>The overall atmosphere conveys confidence and determination</prompt>
                    Activity/Theme: Explain what's happening in the scene or the main theme.
                    Example: <prompt>she shares knowledge about AI tech with people from all walks of life</prompt>
                    Style/Visual reference: Indicate a specific style or visual reference.
                    Example: <prompt>in the style of a TedX talk</prompt>

                By following this structure, you'll create prompts rich in details that will guide Flux to generate precise and captivating images. Don't hesitate to experiment and adjust your prompt based on the results obtained!

                ALSO IMPORTANT:
                - You have to separate every thing in the prompt even the background by First, second, third, ...:
                    Never do "A man hugging his dog at the park."
                    Instead do "First, a park. Second, a man hugging his dog at the park"
                - NEVER use the word background
                - The prompt has to be in english